### ISSUE TITLE
Some UI-related improvements

### ISSUE THREAD

**Issue by SpaceFrrog** [theachoem/storypad#165]
Dear Developer,
first of all big praise for this great app.
A few changes regarding the UI would be good to better comply with the Material Design 3 guidelines.

1. The color of the Status Bar should be the same as the color of the Top App Bar
2. For better readability the Date Picker (when adding a new story/note) should match the Material Design.
   For example like in the picture below:
![Screenshot_20220826-194039](https://user-images.githubusercontent.com/105725665/186962198-d3a27837-d4de-437e-8ed8-fac441eeeeb6.png)

Thanks for your effort.

**Comment by theachoem** [comment]
@Gunter08 Thank you for raising the issue here, we are really glad that the community helps us raise the issue on GitHub. We are working on it.

**Comment by theachoem** [comment]
- [x] Transparent app bar fixed: https://github.com/juniorise/spooky-mb/commit/24cf3b3c2c1f8d10e6c2b6117327bcb66a931b5d
- [ ] Date picker: we still consider it, if most users like your idea, we will go for it. Anways, the current date picker look okay.
