### ISSUE TITLE
where is firebase_options.dart ?

### ISSUE THREAD

**Issue by atfa** [theachoem/storypad#174]
Main.dart line 33 is:
`import 'package:spooky/firebase_options.dart';
`
But there is not file **firebase_options.dart** in the **lib** dir.

**Comment by theachoem** [comment]
@atfa It's credential file, we ignored it before push to GitHub. We use flutterfire to generate firebase_options.dart. To generate, we need firebase cli & flutterfire:

```s
firebase login
flutterfire configure
```
