### ISSUE TITLE
Let system theme be just dark or light so I can use custom color 

### ISSUE THREAD

**Issue by Hedronmx** [theachoem/storypad#206]
Hello! I am loving your app! I have a few suggestions but I'll make separate issues later.

First suggestion is to let the app follow the system dark or light theme but with the ability to use a custom color.

Right now you have to use dynamic color if you want automatic light and dark theme

Thanks for the amazing app

**Comment by theachoem** [comment]
Thank @Hedronmx, let's see what we can do!

**Comment by ishanvaghani** [comment]
@theachoem Recently I started open source contribution. Can i start working on this issue?
