### ISSUE TITLE
Violates material guidelines

### ISSUE THREAD

**Issue by electr1fy0** [theachoem/storypad#218]
Settings does not belong to the Navigation Bar according to MD guidelines. You should move it to a more hidden place.
<img width="993" alt="image" src="https://github.com/juniorise/spooky-mb/assets/87616300/3ba9e66b-5ecf-4407-9a0c-d5194ce0e2d4">

**Comment by electr1fy0** [comment]
Also,
<img width="494" alt="image" src="https://github.com/juniorise/spooky-mb/assets/87616300/226cc19d-9a47-4758-9816-e12c1915b972">

This implies that perhaps Navigation Bar is not the best element choice for an app like this.

**Comment by theachoem** [comment]
@electr1fy0 Any suggestion is appreciated.

**Comment by theachoem** [comment]
This is fixed now!
