### ISSUE TITLE
Steps for contribution

### ISSUE THREAD

**Issue by siddesh3101** [theachoem/storypad#220]
How can I contribute to this project?
Can someone guide me with the steps to clone this project?

**Comment by theachoem** [comment]
@siddesh3101, If you are interested in contributing to this project, you can fork this project. 
- To run, you can run on dev flavor. I pushed all public credentials needed.
- To submit code, push to a branch of your forked repo, then make a PR in this repository.
- Let me know if you need anything.

![image](https://github.com/juniorise/spooky-mb/assets/29684683/20a02de6-03b0-4064-88c6-2e3978882ac3)

**Comment by dongorias** [comment]
Hello @theachoem , I have fork the project and when I do **flutter pub get** I get this error.

```
Git error. Command: `git clone --mirror git@github.com:juniorise/flutter_weather_bg_null_safety.git /Users/donarias/.pub-cache/git/cache/flutter_weather_bg_null_safety-5182e2ce70ac8802940fa4061dec57b31b340bfd`
stdout: 
stderr: Cloning into bare repository '/Users/donarias/.pub-cache/git/cache/flutter_weather_bg_null_safety-5182e2ce70ac8802940fa4061dec57b31b340bfd'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit code: 128
```

**Comment by theachoem** [comment]
@dongorias can you change to 84711df4efbce7f9bef9e8e416ba5bda503b62b8 instead?

**Comment by dongorias** [comment]
@theachoem I can't change that.

**Comment by ErichGiusseppe** [comment]
I have the same issue. @theachoem

**Comment by naeemdev** [comment]
same issue 
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit code: 128
