### ISSUE TITLE
Auto sync 

### ISSUE THREAD

**Issue by dgishere** [theachoem/storypad#221]
This will make sure in case we forgot to sync, we can always set to sync daily to ensure the writed progress won't gone.

Even better if story can kept up to date at cloud so if I use the other devices I can continue editing without trying to update the sync and back uping

**Comment by theachoem** [comment]
This seem like a good feature, I'm working on automated release, developer can contribute to this project and publish.

**Comment by theachoem** [comment]
We make syncing much easier now on v2 especially across devices while keep data secure & safe in your drive.
