### ISSUE TITLE
search button nonfunctional (hidden)

### ISSUE THREAD

**Issue by Kelllyyy** [theachoem/storypad#229]
Searching from the home screen is a button in the top right yet it's hidden most of the time by the night mode toggle button in the same location.

Android 11
Spooky 1.4.1

Thanks, it's.. pretty user unfriendly imo.

**Comment by Kelllyyy** [comment]
(setting "theme" to show up in the bottom bar does take care of the issue but until the user gets to that step there's a lot of confusion as two buttons in the same place is not expected behavior)

**Comment by theachoem** [comment]
It's better now on v2!
