### ISSUE TITLE
No named parameter with the name 'controller'.       controller: controller,

### ISSUE THREAD

**Issue by lwy121810** [theachoem/storypad#238]
lib/views/content_reader/local_widgets/content_page_viewer.dart:74:7: Error: No named parameter with the name 'controller'.
      controller: controller,
      ^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill-7.10.2/lib/src/widgets/editor/editor.dart:145:9: Context: Found this candidate, but the arguments don't match.
  const QuillEditor({
        ^^^^^^^^^^^
lib/views/detail/local_widgets/detail_editor.dart:94:7: Error: No named parameter with the name 'controller'.
      controller: controller,
      ^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/flutter_quill-7.10.2/lib/src/widgets/editor/editor.dart:145:9: Context: Found this candidate, but the arguments don't match.
  const QuillEditor({
        ^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_toolbar.dart:56:13: Error: The method 'HistoryButton' isn't defined for the class 'SpToolbarState'.
 - 'SpToolbarState' is from 'package:spooky/widgets/sp_toolbar/sp_toolbar.dart' ('lib/widgets/sp_toolbar/sp_toolbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'HistoryButton'.
            HistoryButton(
            ^^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_toolbar.dart:63:13: Error: The method 'HistoryButton' isn't defined for the class 'SpToolbarState'.
 - 'SpToolbarState' is from 'package:spooky/widgets/sp_toolbar/sp_toolbar.dart' ('lib/widgets/sp_toolbar/sp_toolbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'HistoryButton'.
            HistoryButton(
            ^^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_toolbar.dart:71:13: Error: The method 'ToggleStyleButton' isn't defined for the class 'SpToolbarState'.
 - 'SpToolbarState' is from 'package:spooky/widgets/sp_toolbar/sp_toolbar.dart' ('lib/widgets/sp_toolbar/sp_toolbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ToggleStyleButton'.
            ToggleStyleButton(
            ^^^^^^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_toolbar.dart:78:13: Error: The method 'ToggleStyleButton' isn't defined for the class 'SpToolbarState'.
 - 'SpToolbarState' is from 'package:spooky/widgets/sp_toolbar/sp_toolbar.dart' ('lib/widgets/sp_toolbar/sp_toolbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ToggleStyleButton'.
            ToggleStyleButton(
            ^^^^^^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_toolbar.dart:85:13: Error: The method 'ToggleStyleButton' isn't defined for the class 'SpToolbarState'.
 - 'SpToolbarState' is from 'package:spooky/widgets/sp_toolbar/sp_toolbar.dart' ('lib/widgets/sp_toolbar/sp_toolbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ToggleStyleButton'.
            ToggleStyleButton(
            ^^^^^^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_toolbar.dart:92:13: Error: The method 'ToggleStyleButton' isn't defined for the class 'SpToolbarState'.
 - 'SpToolbarState' is from 'package:spooky/widgets/sp_toolbar/sp_toolbar.dart' ('lib/widgets/sp_toolbar/sp_toolbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ToggleStyleButton'.
            ToggleStyleButton(
            ^^^^^^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_toolbar.dart:99:13: Error: The method 'ToggleStyleButton' isn't defined for the class 'SpToolbarState'.
 - 'SpToolbarState' is from 'package:spooky/widgets/sp_toolbar/sp_toolbar.dart' ('lib/widgets/sp_toolbar/sp_toolbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ToggleStyleButton'.
            ToggleStyleButton(
            ^^^^^^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_toolbar.dart:106:13: Error: The method 'ToggleStyleButton' isn't defined for the class 'SpToolbarState'.
 - 'SpToolbarState' is from 'package:spooky/widgets/sp_toolbar/sp_toolbar.dart' ('lib/widgets/sp_toolbar/sp_toolbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ToggleStyleButton'.
            ToggleStyleButton(
            ^^^^^^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_toolbar.dart:127:13: Error: The method 'ClearFormatButton' isn't defined for the class 'SpToolbarState'.
 - 'SpToolbarState' is from 'package:spooky/widgets/sp_toolbar/sp_toolbar.dart' ('lib/widgets/sp_toolbar/sp_toolbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ClearFormatButton'.
            ClearFormatButton(
            ^^^^^^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_toolbar.dart:177:13: Error: The method 'SelectAlignmentButton' isn't defined for the class 'SpToolbarState'.
 - 'SpToolbarState' is from 'package:spooky/widgets/sp_toolbar/sp_toolbar.dart' ('lib/widgets/sp_toolbar/sp_toolbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'SelectAlignmentButton'.
            SelectAlignmentButton(
            ^^^^^^^^^^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_toolbar.dart:194:13: Error: The method 'SelectHeaderStyleButton' isn't defined for the class 'SpToolbarState'.
 - 'SpToolbarState' is from 'package:spooky/widgets/sp_toolbar/sp_toolbar.dart' ('lib/widgets/sp_toolbar/sp_toolbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'SelectHeaderStyleButton'.
            SelectHeaderStyleButton(
            ^^^^^^^^^^^^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_toolbar.dart:200:13: Error: The method 'ToggleStyleButton' isn't defined for the class 'SpToolbarState'.
 - 'SpToolbarState' is from 'package:spooky/widgets/sp_toolbar/sp_toolbar.dart' ('lib/widgets/sp_toolbar/sp_toolbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ToggleStyleButton'.
            ToggleStyleButton(
            ^^^^^^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_toolbar.dart:207:13: Error: The method 'ToggleStyleButton' isn't defined for the class 'SpToolbarState'.
 - 'SpToolbarState' is from 'package:spooky/widgets/sp_toolbar/sp_toolbar.dart' ('lib/widgets/sp_toolbar/sp_toolbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ToggleStyleButton'.
            ToggleStyleButton(
            ^^^^^^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_toolbar.dart:214:13: Error: The method 'ToggleCheckListButton' isn't defined for the class 'SpToolbarState'.
 - 'SpToolbarState' is from 'package:spooky/widgets/sp_toolbar/sp_toolbar.dart' ('lib/widgets/sp_toolbar/sp_toolbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ToggleCheckListButton'.
            ToggleCheckListButton(
            ^^^^^^^^^^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_toolbar.dart:221:13: Error: The method 'ToggleStyleButton' isn't defined for the class 'SpToolbarState'.
 - 'SpToolbarState' is from 'package:spooky/widgets/sp_toolbar/sp_toolbar.dart' ('lib/widgets/sp_toolbar/sp_toolbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ToggleStyleButton'.
            ToggleStyleButton(
            ^^^^^^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_toolbar.dart:229:13: Error: The method 'ToggleStyleButton' isn't defined for the class 'SpToolbarState'.
 - 'SpToolbarState' is from 'package:spooky/widgets/sp_toolbar/sp_toolbar.dart' ('lib/widgets/sp_toolbar/sp_toolbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ToggleStyleButton'.
            ToggleStyleButton(
            ^^^^^^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_toolbar.dart:236:13: Error: The method 'IndentButton' isn't defined for the class 'SpToolbarState'.
 - 'SpToolbarState' is from 'package:spooky/widgets/sp_toolbar/sp_toolbar.dart' ('lib/widgets/sp_toolbar/sp_toolbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'IndentButton'.
            IndentButton(
            ^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_toolbar.dart:243:13: Error: The method 'IndentButton' isn't defined for the class 'SpToolbarState'.
 - 'SpToolbarState' is from 'package:spooky/widgets/sp_toolbar/sp_toolbar.dart' ('lib/widgets/sp_toolbar/sp_toolbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'IndentButton'.
            IndentButton(
            ^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_color_button.dart:151:16: Error: The method 'QuillIconButton' isn't defined for the class 'SpColorButtonState'.
 - 'SpColorButtonState' is from 'package:spooky/widgets/sp_toolbar/sp_color_button.dart' ('lib/widgets/sp_toolbar/sp_color_button.dart').
Try correcting the name to the name of an existing method, or defining a method named 'QuillIconButton'.
        return QuillIconButton(
               ^^^^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_image_button.dart:41:12: Error: The method 'QuillIconButton' isn't defined for the class 'SpImageButton'.
 - 'SpImageButton' is from 'package:spooky/widgets/sp_toolbar/sp_image_button.dart' ('lib/widgets/sp_toolbar/sp_image_button.dart').
Try correcting the name to the name of an existing method, or defining a method named 'QuillIconButton'.
    return QuillIconButton(
           ^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/swipeable_page_route-0.4.1/lib/src/page_route.dart:60:3: Error: The superclass, 'CupertinoPageRoute', has no unnamed constructor that takes no arguments.
  SwipeablePageRoute({
  ^^^^^^^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_move_cursor_button.dart:22:12: Error: The method 'QuillIconButton' isn't defined for the class 'SpMoveCursurButton'.
 - 'SpMoveCursurButton' is from 'package:spooky/widgets/sp_toolbar/sp_move_cursor_button.dart' ('lib/widgets/sp_toolbar/sp_move_cursor_button.dart').
Try correcting the name to the name of an existing method, or defining a method named 'QuillIconButton'.
    return QuillIconButton(
           ^^^^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_link_style_button.dart:78:16: Error: The method 'QuillIconButton' isn't defined for the class 'SpLinkStyleButtonState'.
 - 'SpLinkStyleButtonState' is from 'package:spooky/widgets/sp_toolbar/sp_link_style_button.dart' ('lib/widgets/sp_toolbar/sp_link_style_button.dart').
Try correcting the name to the name of an existing method, or defining a method named 'QuillIconButton'.
        child: QuillIconButton(
               ^^^^^^^^^^^^^^^
lib/widgets/sp_toolbar/sp_date_button.dart:28:18: Error: Method not found: 'QuillIconButton'.
    return quill.QuillIconButton(
                 ^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

**Comment by theachoem** [comment]
Avoid update the pubspec.lock

**Comment by theachoem** [comment]
It is more simple to run now on v2.0, please retry if you still want to checkout the source code!
